version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${APP}
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
    ports:
      - 5433:5432
    volumes:
      - G:/Desarrollos/db-docker/postgres:/var/lib/postgresql/data